include(ExternalProject)

set(package_name OpenCL)

if (UNIX)
    if (NOT APPLE)
        execute_process(COMMAND "wget https://dl.bintray.com/boostorg/release/1.65.1/source/boost_1_65_1.tar.bz2")
        execute_process(COMMAND "tar xvjf boost_1_65_1.tar.bz2")
        execute_process(COMMAND "cd boost_1_65_1")
        execute_process(COMMAND "./bootstrap.sh")
        execute_process(COMMAND "echo "using gcc : 7.2 : /usr/bin/g++-7 ; " >> tools/build/src/user-config.jam")
        execute_process(COMMAND "./b2 --toolset=gcc-7.2 install")
    else ()
        find_program(BREW brew)
        if(BREW)
            execute_process(COMMAND ${BREW} install boost -y)
        endif()
    endif()
endif()

if (DEFINED ARGUMENTS)
    find_package(${package_name} ${ARGUMENTS} REQUIRED)
else()
    find_package(${package_name} REQUIRED)
endif()